{{- if .Values.istio.enabled }}
apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "21"
  name: default
  namespace: istio-system
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  members:
    - {{ .Values.namespace }}
{{ end }}