{{- if .Values.bluegreen.enabled }}
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-blue-green
  namespace: gitops
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  params:
  - name: HELM_RELEASE_NAME
    type: string
    default: shop-blue-green
    description: The application deployment name
  - name: SOURCE_GIT_URL
    type: string
    default: https://github.com/{{ .Values.github.repository }}/cloud-native-blue-green
    description: The application git repository url
  - name: SOURCE_GIT_REVISION
    type: string
    default: main
    description: The application git repository revision
  - name: CONTEXT_DIR
    type: string
    default: "helm/quarkus-helm-umbrella/chart"
    description: The subdirectory in the git repository
  - name: HELM_RELEASE_VERSION
    type: string
    default: v1.0.0
    description: Helm release version
  - name: NAMESPACE
    type: string
    default: gitops
    description: namespace
  - name: OVERWRITE_VALUES
    type: string
    default: ""
  - name: VALUES_FILE
    type: string
    default: "values/values.yaml" 
  - name: APP
    type: string
    description: discounts or products
  - name: NEW_IMAGE_TAG
    type: string
    default: None
  - name: REPLICA_COUNT
    type: string
    default: None
  - name: STEP
    type: string
  - name: GIT_USER_NAME
    type: string
    default: {{ .Values.github.user }}
  - name: GIT_USER_EMAIL
    type: string
    default: {{ .Values.github.mail }}
  - name: JQ_PATH
    type: string
    default: .metadata  

  workspaces:
  - name: app-source

  tasks:
  - name: git-clone
    taskRef:
      kind: ClusterTask
      name: git-clone
    params:
    - name: url
      value: $(params.SOURCE_GIT_URL)
    - name: revision
      value: $(params.SOURCE_GIT_REVISION)
    - name: deleteExisting
      value: 'true'
    workspaces:
    - name: output
      workspace: app-source


  - name: get-offline-colour
    runAfter:
    - git-clone
    taskRef:
      name: openshift-client
    params:
    - name: SCRIPT
      value: |
        oc get service $(params.APP)-umbrella-offline -n $(params.NAMESPACE) --output="jsonpath={.spec.selector.version}" > $(workspaces.manifest-dir.path)/version
        cat $(workspaces.manifest-dir.path)/version
    workspaces:
    - name: manifest-dir
      workspace: app-source

  - name: create-result-colour
    runAfter:
    - get-offline-colour
    taskSpec:
      steps:
      - name: set-results
        image: registry.access.redhat.com/ubi8/ubi-minimal:8.3
        script: |
          #!/usr/bin/env bash
          cat $(workspaces.source.path)/version
          cat $(workspaces.source.path)/version > tekton/results/version
      results:
      - name: version
      workspaces:
      - name: source
    workspaces:
    - name: source
      workspace: app-source

  - name: change-new-image-tag
    when:
      - input: "$(params.STEP)"
        operator: in
        values: ["new-version"]
    runAfter:
    - create-result-colour
    params:
      - name: CONTEXT_DIR
        value: $(params.CONTEXT_DIR)
      - name: APP
        value: $(params.APP)
      - name: NEW_IMAGE_TAG
        value: $(params.NEW_IMAGE_TAG) 
      - name: COLOUR
        value: $(tasks.create-result-colour.results.version)
      - name: VALUES_FILE
        value: $(params.VALUES_FILE)
      - name: REPLICA_COUNT
        value: $(params.REPLICA_COUNT)
    taskSpec:
      params:
      - name: CONTEXT_DIR
      - name: APP
      - name: NEW_IMAGE_TAG 
      - name: COLOUR
      - name: VALUES_FILE 
      - name: REPLICA_COUNT
      steps:
      - name: change-new-image-tag
        image: registry.access.redhat.com/ubi8/ubi-minimal:8.3
        script: |
          #!/usr/bin/env bash
          cd $(workspaces.source.path)/$(params.CONTEXT_DIR)
          sed -i '/$(params.APP)-$(params.COLOUR)/{n;n;n;s/.*/    tag: $(params.NEW_IMAGE_TAG)/}' $(params.VALUES_FILE)
          cat $(params.VALUES_FILE)
      workspaces:
      - name: source
    workspaces:
    - name: source
      workspace: app-source

  - name: commit-new-image-tag
    runAfter:
    - change-new-image-tag
    taskRef:
      name: git-cli
    params:
      - name: GIT_USER_NAME
        value: $(params.GIT_USER_NAME)
      - name: GIT_USER_EMAIL
        value: $(params.GIT_USER_EMAIL)
      - name: GIT_SCRIPT
        value: |
          cd $(workspaces.source.path)/$(params.CONTEXT_DIR)
          git add $(params.VALUES_FILE)
          git commit -m "$(params.APP)-$(tasks.create-result-colour.results.version)  new image tag $(params.NEW_IMAGE_TAG)"
          git push origin HEAD:$(params.SOURCE_GIT_REVISION)
    workspaces:
    - name: source
      workspace: app-source
  
  - name: change-switch
    when:
      - input: "$(params.STEP)"
        operator: in
        values: ["switch"]
    runAfter:
    - create-result-colour
    params:
      - name: CONTEXT_DIR
        value: $(params.CONTEXT_DIR)
      - name: APP
        value: $(params.APP)
      - name: COLOUR
        value: $(tasks.create-result-colour.results.version) 
      - name: VALUES_FILE
        value: $(params.VALUES_FILE)         
    taskSpec:
      params:
      - name: CONTEXT_DIR
      - name: APP
      - name: COLOUR 
      - name: VALUES_FILE
      steps:
      - name: change-switch
        image: registry.access.redhat.com/ubi8/ubi-minimal:8.3
        script: |
          #!/usr/bin/env bash
          cd $(workspaces.source.path)/$(params.CONTEXT_DIR)
          sed -i '/$(params.APP)NetworkingOnline/{n;s/.*/  version: $(params.COLOUR)/}' $(params.VALUES_FILE)
          cat $(params.VALUES_FILE)
      workspaces:
      - name: source
    workspaces:
    - name: source
      workspace: app-source

  - name: commit-switch
    runAfter:
    - change-switch
    taskRef:
      name: git-cli
    params:
      - name: GIT_USER_NAME
        value: $(params.GIT_USER_NAME)
      - name: GIT_USER_EMAIL
        value: $(params.GIT_USER_EMAIL)
      - name: GIT_SCRIPT
        value: |
          cd $(workspaces.source.path)/$(params.CONTEXT_DIR)
          git add $(params.VALUES_FILE)
          git commit -m "$(params.APP) switch online to $(tasks.create-result-colour.results.version)"
          git push origin HEAD:$(params.SOURCE_GIT_REVISION)
    workspaces:
    - name: source
      workspace: app-source
  - name: change-scale-down-offline
    when:
      - input: "$(params.STEP)"
        operator: in
        values: ["scale-down-offline"]
    runAfter:
    - create-result-colour
    params:
      - name: CONTEXT_DIR
        value: $(params.CONTEXT_DIR)
      - name: APP
        value: $(params.APP)
      - name: NEW_IMAGE_TAG
        value: $(params.NEW_IMAGE_TAG) 
      - name: COLOUR
        value: $(tasks.create-result-colour.results.version) 
      - name: VALUES_FILE
        value: $(params.VALUES_FILE)            
    taskSpec:
      params:
      - name: CONTEXT_DIR
      - name: APP
      - name: NEW_IMAGE_TAG 
      - name: COLOUR 
      - name: VALUES_FILE   
      steps:
      - name: scale-down-offline
        image: registry.access.redhat.com/ubi8/ubi-minimal:8.3
        script: |
          #!/bin/bash
          cd $(workspaces.source.path)/$(params.CONTEXT_DIR)
          COLOUR=$(params.COLOUR)
          if [ $COLOUR = "blue" ]
          then
            NEW_COLOUR="green"
          else
            NEW_COLOUR="blue"
          fi
          echo $NEW_COLOUR

          sed -i "/$(params.APP)NetworkingOffline/{n;s/.*/  version: $NEW_COLOUR/}" $(params.VALUES_FILE)
          
          sed -i "/$(params.APP)-$NEW_COLOUR/{n;s/.*/  replicaCount: 1/}" $(params.VALUES_FILE)
          sed -i "/$(params.APP)-$NEW_COLOUR/{n;n;n;s/.*/    tag: $(params.NEW_IMAGE_TAG)/}" $(params.VALUES_FILE)
          sed -i "/$(params.APP)-$NEW_COLOUR/{n;n;n;n;s/.*/  mode: offline/}" $(params.VALUES_FILE)
          
          cat $(params.VALUES_FILE)
      workspaces:
      - name: source
    workspaces:
    - name: source
      workspace: app-source

  - name: commit-scale-down-offline
    runAfter:
    - change-scale-down-offline
    taskRef:
      name: git-cli
    params:
      - name: GIT_USER_NAME
        value: $(params.GIT_USER_NAME)
      - name: GIT_USER_EMAIL
        value: $(params.GIT_USER_EMAIL)
      - name: GIT_SCRIPT
        value: |
          cd $(workspaces.source.path)/$(params.CONTEXT_DIR)
          git add $(params.VALUES_FILE)
          git commit -m "$(params.APP) scale down offline"
          git push origin HEAD:$(params.SOURCE_GIT_REVISION)
    workspaces:
    - name: source
      workspace: app-source

  - name: switch-rollback
    when:
      - input: "$(params.STEP)"
        operator: in
        values: ["switch-rollback"]
    runAfter:
    - create-result-colour
    params:
      - name: CONTEXT_DIR
        value: $(params.CONTEXT_DIR)
      - name: APP
        value: $(params.APP)
      - name: COLOUR
        value: $(tasks.create-result-colour.results.version) 
      - name: VALUES_FILE
        value: $(params.VALUES_FILE)         
    taskSpec:
      params:
      - name: CONTEXT_DIR
      - name: APP
      - name: COLOUR 
      - name: VALUES_FILE
      steps:
      - name: change-switch
        image: registry.access.redhat.com/ubi8/ubi-minimal:8.3
        script: |
          #!/usr/bin/env bash
          cd $(workspaces.source.path)/$(params.CONTEXT_DIR)

          COLOUR=$(params.COLOUR)
          if [ $COLOUR = "blue" ]
          then
            NEW_COLOUR="green"
          else
            NEW_COLOUR="blue"
          fi
          echo $NEW_COLOUR

          sed -i "/$(params.APP)NetworkingOnline/{n;s/.*/  version: $NEW_COLOUR/}" $(params.VALUES_FILE)
          
          cat $(params.VALUES_FILE)
      workspaces:
      - name: source
    workspaces:
    - name: source
      workspace: app-source

  - name: commit-switch-rollback
    runAfter:
    - switch-rollback
    taskRef:
      name: git-cli
    params:
      - name: GIT_USER_NAME
        value: $(params.GIT_USER_NAME)
      - name: GIT_USER_EMAIL
        value: $(params.GIT_USER_EMAIL)
      - name: GIT_SCRIPT
        value: |
          cd $(workspaces.source.path)/$(params.CONTEXT_DIR)
          git add $(params.VALUES_FILE)
          git commit -m "$(params.APP) switch-rollback online to $(tasks.create-result-colour.results.version)"
          git push origin HEAD:$(params.SOURCE_GIT_REVISION)
    workspaces:
    - name: source
      workspace: app-source
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: shop-e2e-test
  namespace: gitops
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  params:
  - name: TARGET_VERSION
  - name: JQ_PATH
  steps:
  - name: set-results
    image: badouralix/curl-jq
    script: |
      version="none"
      cat $(workspaces.source.path)/url
      while [[ "$version" != "$(params.TARGET_VERSION)" ]]
      do
        sleep 5
        curl $(cat $(workspaces.source.path)/url) | jq -r '$(params.JQ_PATH)' > metadata
        cat metadata
        version=$(jq -r '.version' metadata)
        echo $version
      done
  workspaces:
  - name: source
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: gitops
  name: workspace-pvc-shop-cd-new-version
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
{{ end }}